version: '3.4'

services:
  mempoolbot:
    image: louieo/mempoolbot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - Settings__NotifyMethod=Telegram
      - Settings__MempoolApiUrl=http://mempool.space/api/v1
      - Settings__EconomyRateThreshold=20
      - Settings__NotifyRepeatFrequencyMinutes=1
      - Settings__TelegramBotToken=5621952976:AAH8aYA_G6bkwCudpTouiSLorK75NTGWnbE
      - Settings__SmtpServer=smtp.gmail.com
      - Settings__SmtpUser=test@gmail.com
      - Settings__SmtpPass=auth token here
      - Settings__FromEmail=test@gmail.com
      - Settings__ToEmail=test@gmail.com