version: '3.4'

services:
  mempoolbot.web:
    image: ${DOCKER_REGISTRY-}mempoolbot
    build:
      context: .
      dockerfile: MempoolBot.Web/Dockerfile
    environment:
      - Settings__NotifyMethod=Telegram
      - Settings__MempoolApiUrl=http://mempool.space/api/v1
      - Settings__EconomyRateThreshold=20
      - Settings__NotifyRepeatFrequencyMinutes=1
      - Settings__TelegramBotToken=XXXXXXXXXXX
      - Settings__SmtpServer=smtp.gmail.com
      - Settings__SmtpUser=test@gmail.com
      - Settings__SmtpPass=auth token here
      - Settings__FromEmail=test@gmail.com
      - Settings__ToEmail=test@gmail.com